add test project filter
CycloneDX/cyclonedx-dotnet pull request #246
Opened 2020-10-02 13:34 UTC by Bertk

check  `IsTestProject` in csproj  (resolves #43)
```
    <IsTestProject>true</IsTestProject>
```

2020-10-09 22:47 UTC, coderpatros requested changes
Hi @Bertk, looks pretty good. There's just a few tweaks I'd like.

2020-10-09 22:47 UTC, coderpatros commented on CycloneDX.Core/Services/IProjectFileService.cs
>      }
Can you please change the `excludeDev` parameter on `IProjectFileService` to something like `excludeTestProjects`? `excludeDev` makes me think it is excluding development dependencies like analyzers, etc.

2020-10-09 22:47 UTC, coderpatros commented on CycloneDX/Program.cs
>                  }
Can you add a command line parameter like `--exclude-test-projects` to control whether test projects are excluded or not? They cover slightly different scenarios.

2020-10-10 08:45 UTC, Bertk commented on CycloneDX.Core/Services/IProjectFileService.cs
>      }
Done.

2020-10-10 08:46 UTC, Bertk commented on CycloneDX/Program.cs
>                  }
Done

2020-10-17 10:41 UTC, Bertk commented
> Hi @Bertk, looks pretty good. There's just a few tweaks I'd like.

All tweaks are implemented.

2020-10-18 05:56 UTC, coderpatros commented
Thanks @Bertk I'll try to get your PRs merged, and a new release done, over the next few days

2020-10-20 10:01 UTC, coderpatros approved these changes

2020-10-20 10:41 UTC, merged