use central package management
CycloneDX/cyclonedx-dotnet pull request #638
Opened 2022-12-14 08:49 UTC by Bertk

- use central package management

2022-12-14 12:06 UTC, coderpatros requested changes

2022-12-14 12:06 UTC, coderpatros commented on .gitpod.yml
>        "$DOTNET_ROOT/dotnet-install.sh" --channel 5.0 --install-dir "$DOTNET_ROOT"
You can drop these versions of the SDK from the gitpod config too

2022-12-14 12:06 UTC, coderpatros commented on semver.txt
> +3.0.0
Don't update this yet. I'll bump the version after merge and before release.

2022-12-16 09:01 UTC, Bertk commented
@coderpatros I resolved all the comments. The tests for my local build are green ;-)
<img width="283" alt="image" src="https://user-images.githubusercontent.com/2315215/208061974-5e7603c8-660b-4774-bc08-5abfd5b4adce.png">

2023-03-03 08:02 UTC, Furbyv commented
Any updates on this?

2023-03-06 14:33 UTC, Bertk commented
> Thanks for the PR @Bertk, can you do a find and replace on all the `FileInfo.FromFilename` calls to address the build warnings too?

Please review again. Done.

2023-03-24 09:34 UTC, tomkuipers commented
Any updates on this?

2023-04-03 07:50 UTC, closed without merging