fix: Add additional log context when reference can not be found
CycloneDX/cyclonedx-dotnet pull request #662
Opened 2023-03-07 15:50 UTC by shawner18

I ran into an issue where the BOM was failing to generate due to dependency resolution issues. The current logging was not clear enough to identify the source of the issue, since we had many projects and many dependencies.

**Original output**
Dependency ([2.29.0, )) with version range ([2.29.0, )) did not resolve to a specific version.
Unable to locate valid bom ref for my.library [2.29.0, )

**Enhanced output**
Dependency (my.library) with version range ([2.29.0, )) referenced by (Name:my.other.library Version:1.18.26) in did not resolve to a specific version.
Unable to locate valid bom ref for my.library [2.29.0, ) referenced in (Name: my.other.library Version: 1.18.26)

2023-05-25 07:17 UTC, adcorduneanu commented
Any fix for this one?

2023-09-27 19:16 UTC, CodeTigerCloud commented
Hello shawner18,

I'd like to merge this, but the sign-off is missing. 
Could you add it please?

See here: https://github.com/CycloneDX/cyclonedx-dotnet/pull/662/checks?check_run_id=11826932593

2023-09-27 20:33 UTC, shawner18 commented
> Hello shawner18,
> 
> I'd like to merge this, but the sign-off is missing. Could you add it please?
> 
> See here: https://github.com/CycloneDX/cyclonedx-dotnet/pull/662/checks?check_run_id=11826932593

Done, sorry about that

2023-09-28 19:03 UTC, CodeTigerCloud requested changes
Yeah, sorry :(
I just saw this now

2023-09-28 19:03 UTC, mtsfoni commented on CycloneDX/Services/ProjectAssetsFileService.cs
> +                            Console.Error.WriteLine($"Dependency ({dependency.Key}) with version range ({dependency.Value}) referenced by (Name:{runtimePackage.Name} Version:{runtimePackage.Version})
The "in" (column 201) is misplaced in the string literal here. Maybe you wanted to print another field after it? Or it's an editing artefact.

2023-09-28 23:33 UTC, shawner18 commented on CycloneDX/Services/ProjectAssetsFileService.cs
> +                            Console.Error.WriteLine($"Dependency ({dependency.Key}) with version range ({dependency.Value}) referenced by (Name:{runtimePackage.Name} Version:{runtimePackage.Version})
fixed the text

2023-09-29 13:58 UTC, CodeTigerCloud approved these changes

2023-10-01 17:10 UTC, merged

2024-03-19 15:32 UTC, Kubana commented
Hi I am trying to generate BOM file for my .sln and I keep getting as well similar error:
"Unable to locate valid bom ref for NETStandard.Library [2.0.1, )" 
And couple of these: "Dependency (NETStandard.Library) with version range ([2.0.1, )) referenced by (Name:Microsoft.Azure.Storage.Queue Version:11.1.7) did not resolve to a specific version."

The thing is when I go .csproj after .csproj everything goes smooth I mean the latter error keeps popping up but the BOM gets generated regardless. And another thing is when I am looking for something that references NETStandard.Library with version 2.0.1 - there is nothing ... I don't know maybe I'm just blind or looking somewhere else